export const categoryList = [
  {
    id: 1,
    title: 'Những lưu ý khi thiết kế và thi công nhà cửa',
    content: 'abc',
    image: '98324380.png',
    valid_flag: 1,
    date: '03/04/2023',
    category_id: 1,
  },
  {
    id: 2,
    title: 'Những lưu ý khi thiết kế và thi công nhà cửa',
    content: 'abc',
    image: '98324380.png',
    valid_flag: 1,
    date: '03/04/2023',
    category_id: 2,
  },
  {
    id: 3,
    title: 'Những lưu ý khi thiết kế và thi công nhà cửa',
    content: 'abc',
    image: '98324380.png',
    valid_flag: 1,
    date: '03/04/2023',
    category_id: 1,
  },
  {
    id: 4,
    title: 'Những lưu ý khi thiết kế và thi công nhà cửa',
    content: 'abc',
    image: '98324380.png',
    valid_flag: 1,
    date: '03/04/2023',
    category_id: 3,
  },
  {
    id: 5,
    title: 'Những lưu ý khi thiết kế và thi công nhà cửa',
    content: 'abc',
    image: '98324380.png',
    valid_flag: 1,
    date: '03/04/2023',
    category_id: 4,
  },
];
