export const customerList = [
  {
    id: 1,
    email: 'nguyenvanteo@gmail.com',
    full_name: 'Nguyen Van Teo',
    birthday: '1/1/2001',
    gender: 'male',
    phone_number: '0983742843',
    location: 'Hai Chau, Da Nang',
  },
  {
    id: 2,
    email: 'nguyenvanteo@gmail.com',
    full_name: 'Nguyen Van Teo',
    birthday: '1/1/2001',
    gender: 'male',
    phone_number: '0983742843',
    location: 'Hai Chau, Da Nang',
  },
  {
    id: 3,
    email: 'nguyenvanteo@gmail.com',
    full_name: 'Nguyen Van Teo',
    birthday: '1/1/2001',
    gender: 'male',
    phone_number: '0983742843',
    location: 'Hai Chau, Da Nang',
  },
  {
    id: 4,
    email: 'nguyenvanteo@gmail.com',
    full_name: 'Nguyen Van Teo',
    birthday: '1/1/2001',
    gender: 'male',
    phone_number: '0983742843',
    location: 'Hai Chau, Da Nang',
  },
  {
    id: 5,
    email: 'nguyenvanteo@gmail.com',
    full_name: 'Nguyen Van Teo',
    birthday: '1/1/2001',
    gender: 'male',
    phone_number: '0983742843',
    location: 'Hai Chau, Da Nang',
  },
];
